# PyTorch Tensor Foundations
Short notes I wrote while stepping through tensor basics

In [1]:
import torch
import numpy as np

### Device check
Keep everything on CPU unless a GPU is actually available.

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

### Building tensors
Start from plain data, NumPy, and other tensors to see how types carry over.

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

From NumPy to torch (shape and dtype stay the same).

In [4]:
np_array = np.array(data, dtype=np.float32)
x_np = torch.from_numpy(np_array)
x_np, x_np.dtype

(tensor([[1., 2.],
         [3., 4.]]),
 torch.float32)

Clone an existing tensor and override dtype when needed.

In [5]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float32)
x_ones, x_rand

(tensor([[1, 1],
         [1, 1]]),
 tensor([[0.1447, 0.8444],
         [0.1770, 0.5319]]))

Random and constant initializers with explicit shapes.

In [6]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.6151, 0.2206, 0.1002],
         [0.0292, 0.8685, 0.2241]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

### Tensor attributes
Shape, dtype, and device show up as properties.

In [7]:
tensor = torch.rand(3, 4, device=device)
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

### Basic ops
Most NumPy habits carry over: slicing, joining, math, and in-place operations.

In [8]:
tensor = torch.ones((4, 4))
first_row = tensor[0]
first_col = tensor[:, 0]
last_col = tensor[:, -1]
tensor[:, 1] = 0
tensor, first_row, first_col, last_col

(tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]),
 tensor([1., 0., 1., 1.]),
 tensor([1., 1., 1., 1.]),
 tensor([1., 1., 1., 1.]))

In [9]:
t1 = torch.cat([tensor, tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])

In [10]:
y = tensor @ tensor.T
z = tensor * tensor
y, z

(tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]))

In [11]:
agg = tensor.sum()
agg_item = agg.item()
agg, agg_item, type(agg_item)

(tensor(12.), 12.0, float)

In-place ops (watch out when autograd is on).

In [12]:
tensor.add_(5)
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

### Bridge with NumPy
CPU tensors share memory with NumPy arrays; edits echo both ways.

In [13]:
t = torch.ones(5)
n = t.numpy()
t, n

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [14]:
t.add_(1)
t, n

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [15]:
n2 = np.ones(5)
t2 = torch.from_numpy(n2)
np.add(n2, 2, out=n2)
t2, n2

(tensor([3., 3., 3., 3., 3.], dtype=torch.float64),
 array([3., 3., 3., 3., 3.]))